name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-24.04
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: panjd123/autograding-command-grader@v1
      with:
        test-name: test
        setup-command: 
        command: echo "666.6" > .autograder_result
        timeout: 10
        max-score: 1000
    - name: Autograding Reporter
      uses: panjd123/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
